Viltrum/urls.py
#test
from django.contrib import admin
from django.urls import path, re_path, include
#Static Files config
from django.conf import settings
from django.conf.urls.static import static
#Reset password config
from django.contrib.auth import views as auth_views

urlpatterns = [
    #Ruta admin
    path('admin/', admin.site.urls),  # Ruta para el panel de administración
    #Ruta autenticación
    path('accounts/', include('django.contrib.auth.urls')),  # Rutas para autenticación
    #Ruta de aplicaciones
    path('', include('core.urls')),  # Incluye todas las rutas de `core.urls` sin prefijo adicional
    path('', include('users.urls')),  # Incluye todas las rutas de `users.urls` sin prefijo adicional
    path('shop/', include('shop.urls', namespace='shop')),
    path('', include('tournaments.urls')), # Incluye todas las rutas de `tournaments.urls` sin prefijo adicional
    path('', include('clasifications.urls')), # Incluye todas las rutas de `clasifications.urls` sin prefijo adicional
    path('', include('sponsors.urls')), # Incluye todas las rutas de `sponsors.urls` sin prefijo adicional
    path('', include('notifications.urls')), # Incluye todas las rutas de `notifications.urls` sin prefijo adicional
    path('', include('chat.urls')), # Incluye todas las rutas de `chat.urls` sin prefijo adicional
    path('', include('explore.urls')), # Incluye todas las rutas de `explore.urls` sin prefijo adicional
    # Rutas para el restablecimiento de contraseña
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt'
    ), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),
    #Manejo de subida de archivos
] 
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('chat/<str:username>', views.get_or_create_chatroom, name='start_chat'),
    path('chat/room/<str:chatroom_name>', views.chat_view, name='chatroom'),
    path('chat/', views.chats_list, name='chats_list'),  
]

tournaments/urls.py
#test
from django.contrib import admin
from django.urls import path, re_path, include
#Static Files config
from django.conf import settings
from django.conf.urls.static import static
#Reset password config
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('tournaments/', views.list_tournaments, name='tournaments'),
    path('tournaments/create/', views.create_tournament, name='crear_torneo'),
    path('tournament/view/<int:tournament_id>', views.view_tournament, name='view_tournament'),
    path('tournament/inscription/<int:tournament_id>', views.tournament_inscription, name='tournament_inscription'),
    path('tournament/inscription/status/<int:inscription_id>/<int:tournament_id>/<int:value>/', views.accept_inscription, name='accept_inscription'),
    path('tournament/inscription/remove/<int:inscription_id>/<int:tournament_id>/',  views.remove_member, name='remove_member'),
    path('tournament/edit/<int:tournament_id>', views.edit_tournament, name='edit_tournament'),
    path('tournament/set/winner/<int:inscription_id>/<int:tournament_id>/', views.set_winner, name='set_winner')
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #Registro
    path('register/', views.create_user, name='register'),
    path('user_logout/', views.user_logout, name='user_logout'),
    #Perfil Jugador - Patrocinador
    path('profile/', views.profile_redirect, name='redirect_profile'),
    path('profile/edit', views.profile_redirect_edit, name='redirect_profile_edit'),
    #Jugador
    path('profile/user/<str:username>/edit', views.edit_profile_user, name='edit_profile_user'),  
    path('profile/user/<str:username>', views.profile_user, name='profile'),
    #Patrocinador  
    path('profile/sponsor/<str:username>', views.profile_sponsor, name='profile_sponsor'),
    path('profile/sponsor/<str:username>/edit', views.edit_profile_sponsor, name='edit_profile_sponsor'),
    #Estadísticas
    path('profile/games_stats/', views.games_stats, name='games_stats'),
    path('profile/add_games_stats/', views.add_games_stats, name='add_games_stats'),
    path('profile/games_stats/edit/<int:game_id>', views.update_game_stats, name='edit_game_stat'),
    path('profile/game_stats/delete/<int:game_id>', views.delete_game_stats, name='delete_game_stats'),
    #Productos  
    path('profile/my-products/', views.product_view, name='product_view'),
    path('profile/products/', views.sponsor_products, name='sponsor_products'),  
    path('profile/product/edit/<int:product_id>', views.update_product, name='edit_product'),
    path('profile/product/delete/<int:product_id>', views.delete_product, name='delete_product'),
    #Verificación
    path('verification/<str:username>', views.verification, name='verification'),
    #Aceptar patrocinadores
    path('my-sponsors/', views.sponsorship, name='my-sponsors'),
    path('my-sponsors/accept/<str:sponsorship>/<int:value>', views.accept_sponsorship, name='accept_sponsoship'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from storages.backends.azure_storage import AzureStorage

# Modelo para información extra de usuarios (Jugadores Y Patrocinadores)
class ExtendedData(models.Model):
    TYPE_CHOICES = [
        ("E", "Elite"),
        ("S", "Sakura"),
        ("S+", "Sakura +"),
        ("V", "Viltrum"),
        ("V+", "Viltrum +")
    ]
    profile_img = models.ImageField(null=True, blank=True, upload_to="images/profileimg", storage=AzureStorage())  # Imagen de perfil
    profile_banner = models.ImageField(null=True, blank=True, upload_to="images/profilebanner", storage=AzureStorage())  # Banner de perfil
    user_description = models.TextField(null=True, blank=True)  # Descripción del usuario}
    viltrum_rank = models.CharField(max_length=3, choices=TYPE_CHOICES, default="E")
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)  # Relación uno a uno con el usuario
    user_identification = models.ImageField(null=True, upload_to="identification", storage=AzureStorage())
    user_photo = models.ImageField(null=True, upload_to="verification_photo", storage=AzureStorage())
    user_verification = models.BooleanField(default=False)
    
    # Campos obligatorios en la creación
    country = CountryField(blank_label='Selecciona tu país', null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)

    @property
    def country_display(self):
        return self.get_country_display()

# Modelo para agregar estadísticas de jugadores
class PlayerStats(models.Model):
    TYPE_CHOICES = [
        ("LoL", "League of Legends"),
        ("D2", "Dota 2"),
        ("CSGO", "Counter-Strike: Global Offensive"),
        ("VAL", "Valorant"),
        ("OW", "Overwatch"),
        ("PUBG", "PlayerUnknown's Battlegrounds"),
        ("FORT", "Fortnite"),
        ("Apex", "Apex Legends"),
        ("R6", "Rainbow Six Siege"),
        ("RL", "Rocket League")
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Relación con el usuario
    user_game = models.CharField(max_length=50)  # Nombre del juego jugado por el usuario
    game = models.CharField(max_length=5, choices=TYPE_CHOICES)  # Juego, limitado a las opciones disponibles
    rank = models.CharField(max_length=50)  # Rango del jugador
    wins = models.IntegerField(default=0)  # Número de victorias
    losses = models.IntegerField(default=0)  # Número de derrotas
    total_played = models.IntegerField(default=0)  # Total de juegos jugados
    is_active = models.BooleanField(default=True)  #Bandera en caso de ser eliminado

    class Meta:
        unique_together = ('user', 'game')  # Asegura que el usuario no pueda repetir el juego con el mismo tipo

# Modelo para agregar productos de patrocinador
class SponsorProducts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=254, null=True)
    product_description = models.CharField(max_length=512, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    product_image = models.ImageField(null=True, blank=True, upload_to="images/sponsorProducts", storage=AzureStorage())
    is_active = models.BooleanField(default=True)

# Modelo para videojuegos
class Videojuego(models.Model):
    nombre = models.CharField(max_length=100)  # Nombre del videojuego
    portada = models.ImageField(upload_to='portadas/', storage=AzureStorage())  # Portada del videojuego

    def __str__(self):
        return self.nombre  # Método para devolver el nombre del juego como string

# Modelo para streams
class Stream(models.Model):
    titulo = models.CharField(max_length=100)  # Título del stream
    descripcion = models.TextField()  # Descripción del stream
    enlace = models.URLField()  # Enlace al stream
    fecha = models.DateTimeField(auto_now_add=True)  # Fecha de creación automática
    imagen = models.ImageField(upload_to='streams/', storage=AzureStorage())  # Imagen asociada al stream

    def __str__(self):
        return self.titulo  # Devuelve el título del stream



class Message(models.Model):
    sender = models.ForeignKey(User, related_name="sent_messages", on_delete=models.CASCADE)
    recipient = models.ForeignKey(User, related_name="received_messages", on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"Message from {self.sender} to {self.recipient}"

class UserGalleryImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='gallery_images/', storage=AzureStorage())
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s image"

class Sponsorship(models.Model):
    TYPE_CHOICES = [
        ("A", "Approved"),
        ("P", "Pending"),
        ("R", "Rejected")
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    sponsor = models.ForeignKey(User, related_name="user_sponsors", on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=20, choices=TYPE_CHOICES)

tournaments/forms.py
from django import forms
from . import models
from django.utils.translation import gettext_lazy as _
from django import forms
from . models import *

class TournamentForm(forms.ModelForm):
    class Meta:
        model = Tournament
        fields = ['name', 'game', 'start_date', 'end_date', 'max_members'] 

class TournamentInscriptionForm(forms.ModelForm):
    class Meta:
        model = TournamentInscription
        fields = ['user', 'tournament']

class TournamentEditForm(forms.ModelForm):
    class Meta:
        model = Tournament
        fields = ['name', 'game', 'start_date', 'end_date', 'max_members'] 

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from . import models
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from django.contrib.auth.models import Group
from django import forms
from .models import Message
from .models import UserGalleryImage


# Formulario para crear usuario jugador "Gamer"
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'last_name', 'password1', 'password2']
    #Deifinir rol de usuario
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            player_group, created = Group.objects.get_or_create(name='Gamer')
            user.groups.add(player_group)
        return user
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Ya hay un usuario registrado con ese nombre")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Ya hay un usuario registrado con ese correo")
        return email
    
# Formulario para crear usuario sponsor "sponsor"
class CreateSponsorForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    #Definir rol de sponsor
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            sponsor_group, created = Group.objects.get_or_create(name='Sponsor')
            user.groups.add(sponsor_group)
        
        return user
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Ya hay un patrocinador registrado con ese nombre")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Ya hay un patrocinador registrado con ese correo")
        return email

#ExtendedData User
class UserExtendedDataForm(forms.ModelForm):
    birthdate = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    class Meta:
        model = models.ExtendedData
        fields = ['country', 'birthdate']

#ExtendedData Sponsor
class SponsorExtendedDataForm(forms.ModelForm):
    class Meta:
        model = models.ExtendedData
        fields = ['country']

# Form to create stream
class StreamForm(forms.ModelForm):
    class Meta:
        model = models.Stream
        fields = ['titulo', 'descripcion', 'enlace', 'imagen']

# Form to create Games
class JuegoForm(forms.ModelForm):
    class Meta:
        model = models.Videojuego
        fields = ['nombre', 'portada']

# Form to add game profile
class PlayerStatsForm(forms.ModelForm):
    class Meta:
        model = models.PlayerStats
        fields = ['user_game', 'game', 'rank', 'wins', 'losses', 'total_played'] 

#Formulario para agregar productos del patrocinador
class SponsorProductsForm(forms.ModelForm):
    class Meta:
        model = models.SponsorProducts
        fields = ['product_name', 'product_description', 'product_image', 'price']

        
# Formulario para editar información del usuario
class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
    
class EditSponsorForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email']

#Formulario para editar información adicional del usuario
class EditExtendedDataUserForm(forms.ModelForm):
    class Meta:
        model = models.ExtendedData
        fields = ['user_description', 'country', 'birthdate']

#Formulario para subir la imagen de perfil
class ProfilePicForm(forms.ModelForm): 
    class Meta:
        model = models.ExtendedData
        fields = ['profile_img']

#Formulario para subir el banner de perfil
class BannerPicForm(forms.ModelForm):
    class Meta:
        model = models.ExtendedData
        fields = ['profile_banner']

class EditGameStat(forms.ModelForm):
    class Meta:
        model = models.PlayerStats
        fields = ['user_game', 'rank', 'wins', 'losses', 'total_played'] 

class EditProduct(forms.ModelForm):
    class Meta:
        model = models.SponsorProducts
        fields = ['product_name', 'product_description', 'product_image', 'price'] 



class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Write your message here...'}),
        }

class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = UserGalleryImage
        fields = ['image']

class VerificationForm(forms.ModelForm):
    class Meta:
        model = models.ExtendedData
        fields = ['user_identification', 'user_photo']

users/templates/create_tournament.html
{% extends 'template.html' %}

{% load static %}

{% block title %}
Viltrum | Inicio
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/tournaments.css' %}">
{% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- Error display block -->
    {% if form.errors %}
    <div class="error-messages">
        <ul>
            {% for field in form %}
            {% for error in field.errors %}
            <li>{{ field.label }}: {{ error }}</li>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <!-- Render fields manually for better control -->
    <div class="tournament-form">
        <h2>Crear Torneo</h2>
        <label for="name">Nombre del Torneo</label>
        {{ form.name }}

        <label for="game">Juego</label>
        {{ form.game }}

        <label for="start_date">Fecha de Inicio</label>
        <input type="date" name="start_date">

        <label for="end_date">Fecha de Fin</label>
        <input type="date" name="end_date">

        <label for="max_members">Máximo de Miembros</label>
        {{ form.max_members }}

        <label for="banner">Banner del Torneo</label>
        {{ form.banner }}

        <button class="btn-create" type="submit">Crear Torneo</button>
</form>
</div>
{% endblock %}

users/templates/edit_product.html
{% extends 'template.html' %}

{% load static %}
{% load extras %}

{% block title %}
Viltrum | Editar Producto {{product.product_name}}
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/editproduct.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
{% endblock %}

{% block content %}
<div class="edit-product-container">
    <div class="header">
        <h2><i class="fas fa-edit"></i> Editar {{product.product_name}}</h2>
    </div>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="product_name">Nombre del producto</label>
            <input type="text" id="product_name" name="product_name" value="{{product.product_name}}" required>
            <label for="price">Precio en USD:</label>
            <input type="number" id="price" name="price" step="0.01" min="0" max="99999999.99" required>
        </div>
        <div class="form-group">
            <label for="product_description">Descripción del producto</label>
            <textarea id="product_description" name="product_description" required>{{product.product_description}}</textarea>
        </div>
        <div class="form-group">
            <label for="product_image">Imagen del producto</label>
            <input type="file" id="product_image" name="product_image" accept="image/*">
        </div>
        <button type="submit"><i class="fas fa-save"></i> Guardar producto</button>
    </form>
</div>
{% endblock %}

users/templates/profile.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Viltrum">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil de {{ profile_user.username }}</title>
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@100;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/myProfile.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>

<body>
    <header>
        <div class="header-container">
            <div class="logo-container">
                <img src="{% static 'images/ninjaviltrum.png' %}" alt="Logo" class="logo">
            </div>
            <nav class="nav-links">
                <a href="{% url 'home' %}">Inicio</a>
                <a href="#">Explorar</a>
                <a href="#">Suscripciones</a>
                <a href="#">Tienda</a>
                <a href="#">Torneos</a>
                <a href="#">Clasificaciones</a>
                <a href="#">Equipos</a>
            </nav>
            <div class="search-bar">
                <input type="text" placeholder="Buscar">
                <button type="submit"><i class="fas fa-search"></i></button>
            </div>
            <div class="auth-buttons">
                {% if user.is_authenticated %}
                <div class="dropdown-profile">
                  <a
                    href="#"
                    aria-haspopup="true"
                    aria-expanded="false"
                    class="user-icon"
                    id="userIcon"
                  >
                    <i class="fa-solid fa-user"></i>
                    {{ user }}
                  </a>
                  <div class="dropdown-content" id="dropdownMenu">
                    <a href="{% url 'redirect_profile' %}">Perfil</a>
                    <a href="{% url 'games_stats' %}">Añadir Estadísticas</a>
                    <a href="{% url 'user_logout' %}">Cerrar sesión</a>
                  </div>
                </div>
                {% else %}
                <a href="{% url 'login' %}" class="login-btn">Iniciar Sesión</a>
                <a href="{% url 'register' %}" class="register-btn">Regístrate</a>
                {% endif %}
            </div>
        </div>
    </header>

    <main>
        <div class="profile-container">
            <div class="profile-header">
                <div class="profile-banner">
                    <img src="{% if profile.profile_banner %}{{ profile.profile_banner.url }}{% else %}http://via.placeholder.com/770x200{% endif %}" alt="Banner">
                </div>
                <div class="profile-header-user">
                    <div class="profile-image">
                        <img src="{% if profile.profile_img %}{{ profile.profile_img.url }}{% else %}https://ui-avatars.com/api/?name={{user}}{% endif %}" alt="Foto de perfil" id="profile-pic">
                        <h2 class="username">{{ profile_user.username }}</h2>
                    </div>
                    <a class="send-message">Enviar mensaje  <i class="fa-solid fa-message"></i></a>
                </div>
                <div class="profile-header-info">
                    <h3>Sobre mí:</h3>
                    <p>{{ profile.about_me|default:"El usuario no ha agregado información aún." }}</p>
                </div>
            </div>
            <div class="profile-body">
                {% if game_exist %}
                <p>Aún no has registrado ningún juego.</p>
                {% else %}
                {% for game in games %}
                <div class="profile-game">
                    {% with image_url='images/'|add:game.game|add:'.png' %}
                    <img src="{% static image_url %}" alt="{{ game.get_game_display }}">
                    {% endwith %}
                    <div class="profile-game-info">
                        <h4>{{ game.user_game }}</h4>
                        <p>
                            Juego: {{ game.get_game_display }} <br>
                            Rango: {{ game.rank }} <br>
                            Winrate: {{ game.winrate|floatformat:2 }}% <br>
                            Tiempo total jugado: {{ game.total_played }}h
                        </p>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>

            <div class="profile-footer">
                <a href="#"><i class="fab fa-facebook-f"></i> Lorem</a>
                <a href="#"><i class="fab fa-twitter"></i> @Lorem</a>
                <a href="#"><i class="fab fa-instagram"></i> Lorem</a>
                <a href="#"><i class="fab fa-youtube"></i> Lorem</a>
                <a href="#"><i class="fa-brands fa-twitch"></i> Lorem</a>
            </div>
        </div>
    </main>

    <footer>
        <div class="footer-container">
            <div class="footer-links">
                <a href="#">Acerca de</a>
                <a href="#">Contacto</a>
                <a href="#">Privacidad</a>
                <a href="#">Términos</a>
                <a href="#">Ayuda</a>
            </div>
            <div class="footer-social">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
                <a href="#"><i class="fab fa-instagram"></i></a>
                <a href="#"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
    </footer>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var userIcon = document.getElementById('userIcon');
            var dropdownMenu = document.getElementById('dropdownMenu');

            userIcon.addEventListener('click', function (event) {
                event.preventDefault();
                dropdownMenu.style.display = dropdownMenu.style.display === 'block' ? 'none' : 'block';
            });

            document.addEventListener('click', function (event) {
                if (!userIcon.contains(event.target) && !dropdownMenu.contains(event.target)) {
                    dropdownMenu.style.display = 'none';
                }
            });
        });
    </script>
</body>

</html>

users/templates/send_message.html
{% extends 'template.html' %}
{% block content %}
    <h2>Send a message to {{ recipient.username }}</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send Message</button>
    </form>
{% endblock %}

users/templates/sponsor_inv.html
{% extends 'template.html' %}

{% load static %}
{% load extras %}

{% block title %}
Viltrum | Mis patrocinios
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/sponsor_inv.css' %}">   
{% endblock %}

{% block content %}
<div class="invitations-container">
    {% for inv in invitations %}
    <div class="invitation-card">
        <h2 class="sponsor-name">{{inv.sponsor}}</h2>
        <div class="actions">
            <a class="btn accept" href="{% url 'accept_sponsoship' sponsorship=inv.id value=1 %}">Aceptar</a>
            <a class="btn reject" href="{% url 'accept_sponsoship' sponsorship=inv.id value=2 %}">Rechazar</a>
        </div>
    </div>
    {% empty %}
    <span class="no-sponsorships">No hay patrocinios pendientes</span>
    {% endfor %}
</div>
{% endblock %}

users/templates/tournaments.html
{% extends 'template.html' %}

{% load static %}

{% block title %}
Viltrum | Torneos
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/tournaments.css' %}">
{% endblock %}

{% block content %}
<div class="tournament-list">
    <h2>Torneos Disponibles</h2>

    <ul>
        {% for tournament in tournaments %}
        <li>
            <div>
                <strong>{{ tournament.name }} - {{ tournament.game }}</strong><br>
                <span class="tournament-status">Estado: {{ tournament.status }}</span><br>
                <span class="time-remaining">Tiempo restante para inscribirse: {{tournament.time_left_to_register|timesince }} </span>
            </div>
            <a href="{% url 'join_tournament' tournament.id %}">Inscribirse</a>
        </li>
        {% empty %}
        <li>No hay torneos disponibles en este momento.</li>
        {% endfor %}
    </ul>

    <a class="new-tournament-link" href="{% url 'crear_torneo' %}">Crear Nuevo Torneo</a>
</div>
{% endblock %}

users/templates/verification_complete.html
{% extends 'template.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/verification.css' %}">
<style>
    main{
    background: linear-gradient(45deg, #2ed341,#225009);
    height: 100vh;
    }
</style>
{% endblock %}

{% block content %}
<div class="complete">
<h1>Perfil verificado</h1>
<p>Tu identidad ha sido verificada, se te ha agregado una insignia de verificación al perfil</p>
<a href="{% url 'home' %}">Volver al Inicio</a>
</div>
{% endblock %}