Viltrum/urls.py
#test
from django.contrib import admin
from django.urls import path, re_path, include
#Static Files config
from django.conf import settings
from django.conf.urls.static import static
#Reset password config
from django.contrib.auth import views as auth_views

urlpatterns = [
    #Ruta admin
    path('admin/', admin.site.urls),  # Ruta para el panel de administración
    #Ruta autenticación
    path('accounts/', include('django.contrib.auth.urls')),  # Rutas para autenticación
    #Ruta de aplicaciones
    path('', include('core.urls')),  # Incluye todas las rutas de `core.urls` sin prefijo adicional
    path('', include('users.urls')),  # Incluye todas las rutas de `users.urls` sin prefijo adicional
    path('shop/', include('shop.urls', namespace='shop')),
    path('', include('tournaments.urls')), # Incluye todas las rutas de `tournaments.urls` sin prefijo adicional
    path('', include('clasifications.urls')), # Incluye todas las rutas de `clasifications.urls` sin prefijo adicional
    path('', include('sponsors.urls')), # Incluye todas las rutas de `sponsors.urls` sin prefijo adicional
    path('', include('notifications.urls')), # Incluye todas las rutas de `notifications.urls` sin prefijo adicional
    path('', include('chat.urls')), # Incluye todas las rutas de `chat.urls` sin prefijo adicional
    path('', include('explore.urls')), # Incluye todas las rutas de `explore.urls` sin prefijo adicional
    # Rutas para el restablecimiento de contraseña
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt'
    ), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),
    #Manejo de subida de archivos
] 
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('chat/<str:username>', views.get_or_create_chatroom, name='start_chat'),
    path('chat/room/<str:chatroom_name>', views.chat_view, name='chatroom'),
    path('chat/', views.chats_list, name='chats_list'),  
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'  # Agrega esto para el namespace

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
]

shop/models.py
# shop/models.py
from django.db import models
from django.contrib.auth.models import User  # Usamos el modelo de usuario para los patrocinadores
from storages.backends.azure_storage import AzureStorage

class Product(models.Model):
    sponsor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="products")
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='products/images/', storage=AzureStorage())
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from users.forms import SponsorProductsForm  # Importamos el formulario existente
from .models import Product
from django.contrib.auth.decorators import login_required
from users.models import SponsorProducts

def product_list(request):
    products = SponsorProducts.objects.filter(is_active=True)
    return render(request, 'shop/product_list.html', {'products': products})
def product_detail(request, pk):
    """Muestra los detalles de un producto individual."""
    product = SponsorProducts.objects.get(pk=pk)
    return render(request, 'shop/product_detail.html', {'product': product})

@login_required
def add_product(request):
    """Permite a los patrocinadores agregar un nuevo producto."""
    if request.method == 'POST':
        form = SponsorProductsForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.sponsor = request.user
            product.save()
            return redirect('shop:product_list')
    else:
        form = SponsorProductsForm()
    return render(request, 'shop/add_product.html', {'form': form})

shop/templates/shop/product_detail.html
{% extends 'template.html' %}

{% block title %}{{ product.product_name }}{% endblock %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'shop/product_detail.css' %}">
<style>
    .star {
    position: absolute;
    width: 60px; /* Tamaño de la "estrella" (imagen) */
    height: 60px;
    background-image: url('{{ product.product_image.url }}'); /* Imagen del producto */
    background-size: cover;
    background-position: center;
    border-radius: 50%;
    animation: moveAndRotate linear infinite;
}
</style>
{% endblock %}

{% block content %}
<div class="star-field" id="star-field"></div>
<div class="product-detail">
    <div class="product-image-container">
        <img src="{{ product.product_image.url }}" alt="{{ product.product_name }}" class="product-image">
    </div>
    <div class="product-info">
        <h1>{{ product.product_name }}</h1>
        <p class="product-description">{{ product.product_description }}</p>
        <p class="product-price">Precio: ${{ product.price }} MXN</p>
        <p class="product-sponsor">Patrocinador: <a href="{% url 'profile_sponsor' product.user.username %}">{{ product.user.username }}</a></p>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script>
    // Crear estrellas en el fondo
    const starField = document.getElementById('star-field');
    const numberOfStars = 50;  // Número de estrellas

    // Función para generar estrellas aleatorias
    function generateStars() {
        for (let i = 0; i < numberOfStars; i++) {
            const star = document.createElement('div');
            star.classList.add('star');
            // Generar una posición aleatoria para cada estrella
            star.style.left = `${Math.random() * 100}%`;
            star.style.animationDuration = `${Math.random() * 4 + 6}s`; // Duración de rotación aleatoria
            star.style.animationDelay = `${Math.random() * 1}s`; // Retraso aleatorio en la animación
            starField.appendChild(star);
        }
    }

    // Generar estrellas al cargar la página
    generateStars();
</script>
{% endblock %}

shop/templates/shop/product_list.html
{% extends 'template.html' %}
{% load static %}  <!-- Cargar archivos estáticos -->

{% block title %}
Viltrum | Tienda de Productos
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'shop/product_list.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
  <h2>Tienda de Productos</h2>
  <div class="shop-body">
    {% if products %}
    {% for product in products %}
    <div class="shop-product-item">
      <!-- Enlace para el producto -->
      <a href="{% url 'shop:product_detail' product.id %}" class="product-link">
        <img src="{% if product.product_image %}{{ product.product_image.url }}{% else %}https://ui-avatars.com/api/?name={{ product.product_name }}{% endif %}" alt="{{ product.product_name }}" class="product-image">
      </a>
      
      <!-- Información del producto -->
      <div class="shop-product-info">
        <!-- Enlace para el perfil del patrocinador -->
        <a href="{% url 'profile_sponsor' product.user.username %}" class="sponsor-link">
          <h3>{{ product.user.username }}</h3>
        </a>
        <p>{{ product.product_name }}</p>
      </div>
    </div>
  {% endfor %}
  
  
  
    {% else %}
      <p class="no-products">Actualmente no hay productos disponibles en la tienda.</p>
    {% endif %}
  </div>
</div>
{% endblock %}